package program

const (
	// UnkUniform ...
	UnkUniform Type = iota
	// FltUniform ...
	FltUniform
	// IntUniform ...
	IntUniform
	// Vec4Uniform ...
	Vec4Uniform
	// Vec3Uniform ...
	Vec3Uniform
	// Vec2Uniform ...
	Vec2Uniform
	// Mat4Uniform ...
	Mat4Uniform
	// Tex2DUniform ...
	Tex2DUniform
)

const (
	// UnkDst ...
	UnkDst Destination = iota
	// ModelDst ...
	ModelDst
	// ViewDst ...
	ViewDst
	// ProjectionDst ...
	ProjectionDst
	// ColorDst ...
	ColorDst
	// LightPosDst ...
	LightPosDst
	// LightColor ...
	LightColorDst
)

const (
	UModelName      = "uModel"
	UViewName       = "uView"
	UProjectionName = "uProjection"

	ULightPositionName = "uLightPos"
	ULightColorName    = "uLightColor"

	UColorName = "uColor"
)

const (
	// UCMesh ...
	UCMesh UniformCat = iota
	// UCLight ...
	UCLight
)
